-- Create scores table in Supabase
CREATE TABLE scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    score INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE scores ENABLE ROW LEVEL SECURITY;

-- Create policy to allow anonymous inserts
CREATE POLICY "Allow anonymous inserts" ON scores
    FOR INSERT WITH CHECK (true);

-- Create policy to allow anonymous selects
CREATE POLICY "Allow anonymous selects" ON scores
    FOR SELECT USING (true);

-- Create index on score for better performance when querying top scores
CREATE INDEX idx_scores_score ON scores(score DESC);

-- Create index on created_at for time-based queries
CREATE INDEX idx_scores_created_at ON scores(created_at DESC);
